In [1]:
# NOTES
# column label, index label, index axis = 0, column axis = 1
# missing values - NaN
# variables - categorical, numerical
# categorical - data which are non numerical
# outlayer - biggest or the smallest value
# percentile, median, mean, variance, standard variation,
# mode, bivariate analysis
# kaggle - analytical competition platform

In [2]:
# series - one dimensional
# frame - multi dimensional
# np.nan - pass empty/null values

In [5]:
import pandas as pd
dates = pd.date_range('20230105', periods = 6)
dates

DatetimeIndex(['2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10'],
              dtype='datetime64[ns]', freq='D')

In [8]:
import numpy as np
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns = list('ABCD'))
df

                   A         B         C         D
2023-01-05 -0.692743  0.632124 -0.789408 -0.198656
2023-01-06  1.035411 -0.563004 -0.842174 -0.611752
2023-01-07  0.077738  0.820806 -0.376465  1.137063
2023-01-08 -0.913729 -0.904935 -0.470569  0.499776
2023-01-09 -0.040892 -0.839779 -0.196583 -0.049660
2023-01-10 -0.920483  2.064282  0.616279  0.230568

In [9]:
# to insert a cell -- go to insert tab

In [27]:
labels = ['w', 'x', 'y', 'z']
ab = [10, 20, 30, 40]
ar = np.array([10, 20, 30, 40])
dict = {'w': 10, 'x': 40, 'y':30, 'z': 40}

In [28]:
labels

['w', 'x', 'y', 'z']

In [29]:
ar.mean()

25.0

In [30]:
pd.Series(data=ab)

0    10
1    20
2    30
3    40
dtype: int64

In [31]:
pd.Series(data=ab, index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [32]:
pd.Series(ab, labels)

w    10
x    20
y    30
z    40
dtype: int64

In [33]:
pd.Series(ar)

0    10
1    20
2    30
3    40
dtype: int32

In [34]:
pd.Series(dict)

w    10
x    40
y    30
z    40
dtype: int64

In [36]:
dict = {'w':10, 'x':[40, 39,29], 'y':30, 'z':['a', 'd', 'test']}
pd.Series(dict)

w              10
x    [40, 39, 29]
y              30
z    [a, d, test]
dtype: object

In [43]:
sports1 = pd.Series([1,2,3,4], index = ['Cricket', 'Football', 'Basketball', 'Golf'])
sports1

Cricket       1
Football      2
Basketball    3
Golf          4
dtype: int64

In [44]:
sports2 = pd.Series([1,2,5,4], index = ['Cricket', 'Football', 'Basketball', 'Golf'])
sports2

Cricket       1
Football      2
Basketball    5
Golf          4
dtype: int64

In [45]:
sports1['Cricket']

1

In [46]:
sports1 + sports2

Cricket       2
Football      4
Basketball    8
Golf          8
dtype: int64

In [56]:
from numpy.random import randn

In [71]:
dataframe = pd.DataFrame(randn(10,5), index = ' A B C D E F G H I J'.split(), columns = 'Score1 Score2 Score3 Score4 Score5'.split())
dataframe

     Score1    Score2    Score3    Score4    Score5
A  0.184128 -1.005955 -0.341980 -0.044724  0.278441
B -0.580894 -0.151515 -1.147434 -0.611000 -1.189517
C  0.872266 -0.015542  1.166682 -2.158610  0.756204
D -1.690499 -0.348794 -1.729515  0.696312  0.564962
E  0.479861 -0.295945 -0.420309 -0.859614 -0.407915
F  1.247578 -1.829384 -1.596518  0.690312  0.928122
G  1.586536  0.401306 -1.269689  0.469206  1.303859
H  1.231284  0.229482  0.273608 -0.666784 -0.197579
I  0.486021  0.860458 -2.054327 -0.807341 -2.895766
J  1.092305 -0.589334  0.989184 -0.038086  1.222682

In [72]:
np.random.seed(5)
np.random.randint(1, 20)

4

In [67]:
dataframe

     Score1    Score2    Score3    Score4    Score5
A  0.184128 -1.005955 -0.341980 -0.044724  0.278441
B -0.580894 -0.151515 -1.147434 -0.611000 -1.189517
C  0.872266 -0.015542  1.166682 -2.158610  0.756204
D -1.690499 -0.348794 -1.729515  0.696312  0.564962
E  0.479861 -0.295945 -0.420309 -0.859614 -0.407915
F  1.247578 -1.829384 -1.596518  0.690312  0.928122
G  1.586536  0.401306 -1.269689  0.469206  1.303859
H  1.231284  0.229482  0.273608 -0.666784 -0.197579
I  0.486021  0.860458 -2.054327 -0.807341 -2.895766
J  1.092305 -0.589334  0.989184 -0.038086  1.222682

In [75]:
# seed used to lock random numbers
# using different seeds with same number of values gives same outputs
# using seed we can maintain a set of numbers with the seed numbers

In [8]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(100)
np.random.randint(1,100)

9

In [9]:
dataframe = pd.DataFrame(randn(10,5), index = ' A B C D E F G H I J'.split(), columns = 'Score1 Score2 Score3 Score4 Score5'.split())
dataframe

     Score1    Score2    Score3    Score4    Score5
A -0.893259  1.738260 -1.179703  0.088571 -0.363776
B -0.398300 -0.234715 -1.439737  0.432817  2.304473
C -0.122635  0.015459  0.266016 -0.113795  1.011066
D -1.440771  0.980569  1.376996 -0.230285  0.480924
E -1.266911  0.271005  2.140763  0.475369  0.246525
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440
G -0.464024 -0.057027  0.275930  1.494515  0.566821
H -2.303374  1.377001 -1.187387  0.079393  0.107969
I  0.506951  1.125589 -1.008052  0.354829 -0.702668
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311

In [11]:
dataframe['Score3']

A   -1.179703
B   -1.439737
C    0.266016
D    1.376996
E    2.140763
F   -0.436349
G    0.275930
H   -1.187387
I   -1.008052
J   -0.686599
Name: Score3, dtype: float64

In [14]:
# pass a list of column names in any order necessary
dataframe[['Score2','Score1']]

     Score2    Score1
A  1.738260 -0.893259
B -0.234715 -0.398300
C  0.015459 -0.122635
D  0.980569 -1.440771
E  0.271005 -1.266911
F -2.381583 -1.084174
G -0.057027 -0.464024
H  1.377001 -2.303374
I  1.125589  0.506951
J -1.041134  0.113451

In [16]:
type(dataframe['Score1'])

pandas.core.series.Series

In [17]:
type(dataframe[['Score2','Score1']])

pandas.core.frame.DataFrame

In [19]:
# add a new column
dataframe['Score6'] = dataframe['Score1'] + dataframe['Score2']
dataframe

     Score1    Score2    Score3    Score4    Score5    Score6
A -0.893259  1.738260 -1.179703  0.088571 -0.363776  0.845002
B -0.398300 -0.234715 -1.439737  0.432817  2.304473 -0.633015
C -0.122635  0.015459  0.266016 -0.113795  1.011066 -0.107176
D -1.440771  0.980569  1.376996 -0.230285  0.480924 -0.460202
E -1.266911  0.271005  2.140763  0.475369  0.246525 -0.995905
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440 -3.465757
G -0.464024 -0.057027  0.275930  1.494515  0.566821 -0.521050
H -2.303374  1.377001 -1.187387  0.079393  0.107969 -0.926374
I  0.506951  1.125589 -1.008052  0.354829 -0.702668  1.632540
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311 -0.927683

In [23]:
# remove columns from dataframe
dataframe.drop('Score6', axis = 1)
# axis = 0 for rows
# axis = 1 for columns
# column is not dropped unless inplace input is TRUE

     Score1    Score2    Score3    Score4    Score5
A -0.893259  1.738260 -1.179703  0.088571 -0.363776
B -0.398300 -0.234715 -1.439737  0.432817  2.304473
C -0.122635  0.015459  0.266016 -0.113795  1.011066
D -1.440771  0.980569  1.376996 -0.230285  0.480924
E -1.266911  0.271005  2.140763  0.475369  0.246525
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440
G -0.464024 -0.057027  0.275930  1.494515  0.566821
H -2.303374  1.377001 -1.187387  0.079393  0.107969
I  0.506951  1.125589 -1.008052  0.354829 -0.702668
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311

In [26]:
# add a new column using list
dataframe['Score6'] = dataframe['Score1'] + dataframe['Score2']
dataframe
dataframe.drop('Score6', axis = 1, inplace = True)
dataframe

     Score1    Score2    Score3    Score4    Score5
A -0.893259  1.738260 -1.179703  0.088571 -0.363776
B -0.398300 -0.234715 -1.439737  0.432817  2.304473
C -0.122635  0.015459  0.266016 -0.113795  1.011066
D -1.440771  0.980569  1.376996 -0.230285  0.480924
E -1.266911  0.271005  2.140763  0.475369  0.246525
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440
G -0.464024 -0.057027  0.275930  1.494515  0.566821
H -2.303374  1.377001 -1.187387  0.079393  0.107969
I  0.506951  1.125589 -1.008052  0.354829 -0.702668
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311

In [27]:
# inplace = True -- modify existing objecet
# inplace = False -- return a new modified object

In [28]:
# dropping rows using axis
dataframe.drop('A', axis = 0)
# row will also be dropped only if inlace = true

     Score1    Score2    Score3    Score4    Score5
B -0.398300 -0.234715 -1.439737  0.432817  2.304473
C -0.122635  0.015459  0.266016 -0.113795  1.011066
D -1.440771  0.980569  1.376996 -0.230285  0.480924
E -1.266911  0.271005  2.140763  0.475369  0.246525
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440
G -0.464024 -0.057027  0.275930  1.494515  0.566821
H -2.303374  1.377001 -1.187387  0.079393  0.107969
I  0.506951  1.125589 -1.008052  0.354829 -0.702668
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311

In [30]:
# select columns using
dataframe['Score1']
dataframe.Score1

A   -0.893259
B   -0.398300
C   -0.122635
D   -1.440771
E   -1.266911
F   -1.084174
G   -0.464024
H   -2.303374
I    0.506951
J    0.113451
Name: Score1, dtype: float64

In [35]:
# select rows using location
dataframe.loc['F']

Score1   -1.084174
Score2   -2.381583
Score3   -0.436349
Score4   -2.072412
Score5   -1.295440
Name: F, dtype: float64

In [36]:
# select rows using index location
dataframe.iloc[2]

Score1   -0.122635
Score2    0.015459
Score3    0.266016
Score4   -0.113795
Score5    1.011066
Name: C, dtype: float64

In [38]:
# select a subset of rows and columns
dataframe.loc['A', 'Score1']

-0.8932587211317661

In [40]:
dataframe.loc[['A', 'B'], ['Score1', 'Score2']]

     Score1    Score2
A -0.893259  1.738260
B -0.398300 -0.234715

In [41]:
# conditional selection
dataframe

     Score1    Score2    Score3    Score4    Score5
A -0.893259  1.738260 -1.179703  0.088571 -0.363776
B -0.398300 -0.234715 -1.439737  0.432817  2.304473
C -0.122635  0.015459  0.266016 -0.113795  1.011066
D -1.440771  0.980569  1.376996 -0.230285  0.480924
E -1.266911  0.271005  2.140763  0.475369  0.246525
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440
G -0.464024 -0.057027  0.275930  1.494515  0.566821
H -2.303374  1.377001 -1.187387  0.079393  0.107969
I  0.506951  1.125589 -1.008052  0.354829 -0.702668
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311

In [51]:
dataframe.iloc[5]>0.5

Score1    False
Score2    False
Score3    False
Score4    False
Score5    False
Name: F, dtype: bool

In [42]:
dataframe>0.5

   Score1  Score2  Score3  Score4  Score5
A   False    True   False   False   False
B   False   False   False   False    True
C   False   False   False   False    True
D   False    True    True   False   False
E   False   False    True   False   False
F   False   False   False   False   False
G   False   False   False    True    True
H   False    True   False   False   False
I    True    True   False   False   False
J   False   False   False   False    True

In [52]:
dataframe[dataframe>0.5]
# gets value if its true, if false gives NaN

     Score1    Score2    Score3    Score4    Score5
A       NaN  1.738260       NaN       NaN       NaN
B       NaN       NaN       NaN       NaN  2.304473
C       NaN       NaN       NaN       NaN  1.011066
D       NaN  0.980569  1.376996       NaN       NaN
E       NaN       NaN  2.140763       NaN       NaN
F       NaN       NaN       NaN       NaN       NaN
G       NaN       NaN       NaN  1.494515  0.566821
H       NaN  1.377001       NaN       NaN       NaN
I  0.506951  1.125589       NaN       NaN       NaN
J       NaN       NaN       NaN       NaN  0.946311

In [93]:
dataframe[dataframe['Score1']>0.5]

     Score1    Score2    Score3    Score4    Score5 Countries  Score6
I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0

In [94]:
dataframe[dataframe['Score1']>0.5]['Score2']

I    1.125589
Name: Score2, dtype: float64

In [95]:
# for multiple conditions
# use | and & with parenthesis
dataframe[(dataframe['Score1']>0.5) & (dataframe['Score2'] > 0)]

     Score1    Score2    Score3    Score4    Score5 Countries  Score6
I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0

In [96]:
dataframe

     Score1    Score2    Score3    Score4    Score5 Countries  Score6
A -0.893259  1.738260 -1.179703  0.088571 -0.363776       IND     NaN
B -0.398300 -0.234715 -1.439737  0.432817  2.304473        JP     3.0
C -0.122635  0.015459  0.266016 -0.113795  1.011066       CAN     4.0
D -1.440771  0.980569  1.376996 -0.230285  0.480924        GE     5.0
E -1.266911  0.271005  2.140763  0.475369  0.246525        IT     6.0
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440        PL     7.0
G -0.464024 -0.057027  0.275930  1.494515  0.566821        FY     8.0
H -2.303374  1.377001 -1.187387  0.079393  0.107969        IU     9.0
I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311        IP    11.0

In [92]:
# reset to default index value instead of A to J
dataframe.reset_index()
# index became a row

  index    Score1    Score2    Score3    Score4    Score5 Countries  Score6
0     A -0.893259  1.738260 -1.179703  0.088571 -0.363776       IND     NaN
1     B -0.398300 -0.234715 -1.439737  0.432817  2.304473        JP     3.0
2     C -0.122635  0.015459  0.266016 -0.113795  1.011066       CAN     4.0
3     D -1.440771  0.980569  1.376996 -0.230285  0.480924        GE     5.0
4     E -1.266911  0.271005  2.140763  0.475369  0.246525        IT     6.0
5     F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440        PL     7.0
6     G -0.464024 -0.057027  0.275930  1.494515  0.566821        FY     8.0
7     H -2.303374  1.377001 -1.187387  0.079393  0.107969        IU     9.0
8     I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0
9     J  0.113451 -1.041134 -0.686599 -2.559448  0.946311        IP    11.0

In [91]:
# add new column using series
dataframe['Score6']= pd.Series([3,4,5,6,7,8,9, 10, 11], index="B C D E F G H I J".split())
dataframe

     Score1    Score2    Score3    Score4    Score5 Countries  Score6
A -0.893259  1.738260 -1.179703  0.088571 -0.363776       IND     NaN
B -0.398300 -0.234715 -1.439737  0.432817  2.304473        JP     3.0
C -0.122635  0.015459  0.266016 -0.113795  1.011066       CAN     4.0
D -1.440771  0.980569  1.376996 -0.230285  0.480924        GE     5.0
E -1.266911  0.271005  2.140763  0.475369  0.246525        IT     6.0
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440        PL     7.0
G -0.464024 -0.057027  0.275930  1.494515  0.566821        FY     8.0
H -2.303374  1.377001 -1.187387  0.079393  0.107969        IU     9.0
I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311        IP    11.0

In [89]:
# setting new index value
newindex = 'IND JP CAN GE IT PL FY IU RT IP'.split()
newindex

['IND', 'JP', 'CAN', 'GE', 'IT', 'PL', 'FY', 'IU', 'RT', 'IP']

In [90]:
dataframe['Countries'] = newindex
dataframe

     Score1    Score2    Score3    Score4    Score5 Countries  Score6
A -0.893259  1.738260 -1.179703  0.088571 -0.363776       IND     NaN
B -0.398300 -0.234715 -1.439737  0.432817  2.304473        JP     3.0
C -0.122635  0.015459  0.266016 -0.113795  1.011066       CAN     4.0
D -1.440771  0.980569  1.376996 -0.230285  0.480924        GE     5.0
E -1.266911  0.271005  2.140763  0.475369  0.246525        IT     6.0
F -1.084174 -2.381583 -0.436349 -2.072412 -1.295440        PL     7.0
G -0.464024 -0.057027  0.275930  1.494515  0.566821        FY     8.0
H -2.303374  1.377001 -1.187387  0.079393  0.107969        IU     9.0
I  0.506951  1.125589 -1.008052  0.354829 -0.702668        RT    10.0
J  0.113451 -1.041134 -0.686599 -2.559448  0.946311        IP    11.0

In [98]:
dataframe.set_index('Countries')

             Score1    Score2    Score3    Score4    Score5  Score6
Countries
IND       -0.893259  1.738260 -1.179703  0.088571 -0.363776     NaN
JP        -0.398300 -0.234715 -1.439737  0.432817  2.304473     3.0
CAN       -0.122635  0.015459  0.266016 -0.113795  1.011066     4.0
GE        -1.440771  0.980569  1.376996 -0.230285  0.480924     5.0
IT        -1.266911  0.271005  2.140763  0.475369  0.246525     6.0
PL        -1.084174 -2.381583 -0.436349 -2.072412 -1.295440     7.0
FY        -0.464024 -0.057027  0.275930  1.494515  0.566821     8.0
IU        -2.303374  1.377001 -1.187387  0.079393  0.107969     9.0
RT         0.506951  1.125589 -1.008052  0.354829 -0.702668    10.0
IP         0.113451 -1.041134 -0.686599 -2.559448  0.946311    11.0

In [102]:
# once again ensure that you input inplace = true

In [106]:
dataframe = pd.DataFrame({'Cricket':[1,2,np.nan,4,6,7,2,np.nan], 
                         'Baseball':[5, np.nan, np.nan, 5,7,2,4,5],
                         'Tennis': [1,2,3,4,5,6,7,8]})
dataframe

   Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      NaN       5.0       8

In [110]:
dataframe.dropna()
# by default axis = 0

   Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7

In [111]:
# use axis = 1 for dropping columns with non values
dataframe.dropna(axis=1)

   Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8

In [113]:
dataframe.dropna(thresh=2)
# setting minimum number of null values to drop using threshold

   Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       NaN       2
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      NaN       5.0       8

In [116]:
dataframe.fillna(value=0)
# replace empty values using value

   Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       0.0       2
2      0.0       0.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      0.0       5.0       8

In [118]:
dataframe['Baseball'].fillna(value=dataframe['Baseball'].mean())

0    5.000000
1    4.666667
2    4.666667
3    5.000000
4    7.000000
5    2.000000
6    4.000000
7    5.000000
Name: Baseball, dtype: float64

In [122]:
# groupby method - groups rows together and perform aggregate functions
# create dataframe as given below
dat = {'CustID':['1001', '1001', '1002', '1002', '1003', '1003'],
      'CustName':['UIPat', 'DatROb', 'Goog', 'Chrysler', 'Ford', 'GM'],
      'ProfitinLakhs':[2005, 3245, 1234, 5544, 7543, 8623]}
dataframe = pd.DataFrame(dat)
dataframe

  CustID  CustName  ProfitinLakhs
0   1001     UIPat           2005
1   1001    DatROb           3245
2   1002      Goog           1234
3   1002  Chrysler           5544
4   1003      Ford           7543
5   1003        GM           8623

In [124]:
CustID_grouped = dataframe.groupby('CustID')
CustID_grouped

In [125]:
CustID_grouped.mean()

C:\Users\hp\AppData\Local\Temp\ipykernel_17476\2458676046.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  CustID_grouped.mean()

        ProfitinLakhs
CustID
1001           2625.0
1002           3389.0
1003           8083.0

In [126]:
CustID_grouped.median()

C:\Users\hp\AppData\Local\Temp\ipykernel_17476\800203475.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  CustID_grouped.median()

        ProfitinLakhs
CustID
1001           2625.0
1002           3389.0
1003           8083.0

In [127]:
CustID_grouped.std()

C:\Users\hp\AppData\Local\Temp\ipykernel_17476\1064751506.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  CustID_grouped.std()

        ProfitinLakhs
CustID
1001       876.812409
1002      3047.630227
1003       763.675324

In [128]:
CustID_grouped.min()

        CustName  ProfitinLakhs
CustID
1001      DatROb           2005
1002    Chrysler           1234
1003        Ford           7543

In [129]:
CustID_grouped.max()

       CustName  ProfitinLakhs
CustID
1001      UIPat           3245
1002       Goog           5544
1003         GM           8623

In [130]:
CustID_grouped.count()

        CustName  ProfitinLakhs
CustID
1001           2              2
1002           2              2
1003           2              2

In [132]:
CustID_grouped.describe()
# gives some imp stats

       ProfitinLakhs                                                       \
               count    mean          std     min     25%     50%     75%
CustID
1001             2.0  2625.0   876.812409  2005.0  2315.0  2625.0  2935.0
1002             2.0  3389.0  3047.630227  1234.0  2311.5  3389.0  4466.5
1003             2.0  8083.0   763.675324  7543.0  7813.0  8083.0  8353.0


           max
CustID
1001    3245.0
1002    5544.0
1003    8623.0

In [133]:
CustID_grouped.describe().transpose()
# also can be written as
#CustID_grouped.describe().T

CustID                      1001         1002         1003
ProfitinLakhs count     2.000000     2.000000     2.000000
              mean   2625.000000  3389.000000  8083.000000
              std     876.812409  3047.630227   763.675324
              min    2005.000000  1234.000000  7543.000000
              25%    2315.000000  2311.500000  7813.000000
              50%    2625.000000  3389.000000  8083.000000
              75%    2935.000000  4466.500000  8353.000000
              max    3245.000000  5544.000000  8623.000000

In [134]:
CustID_grouped.describe().transpose()['1001']

ProfitinLakhs  count       2.000000
               mean     2625.000000
               std       876.812409
               min      2005.000000
               25%      2315.000000
               50%      2625.000000
               75%      2935.000000
               max      3245.000000
Name: 1001, dtype: float64

In [135]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustID         6 non-null      object
 1   CustName       6 non-null      object
 2   ProfitinLakhs  6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [136]:
# concatenation
# by default, add horizontaly
# pd.concat([dafa2, dafa2, dafa3])

In [137]:
# pd.concat([dafa2, dafa2, dafa3], axis = 1)
# to add vertically

In [138]:
# merge
# pd.merge(dafa1, dafa2, how='outer', on='CustID') -- add all
# pd.merge(dafa1, dafa2, how='inner', on='CustID') -- add only available

In [139]:
# join tables or dfs
#table1.join(table2)